### ISSUE TITLE
Channel not appear in the list when joined

### ISSUE THREAD

**Issue by raymand211092** [martinetd/matrirc#13]
console shows me to enter the channels..but I don't get the channels...on the list..

[00:30:03] * JOIN #grupotd_rss
[00:30:03] * #grupotd_rss Idalmisvargas R-Bridge  RayManD system MatterbridgeBot Test 
[00:30:03] * #grupotd_rss End
[00:30:04] * JOIN #GrupoTDFork
[00:30:04] * #GrupoTDFork Telegrambridgebot WhatsAppbridgebot Test  Facebookbridgebot MatterbridgeBot RayManD R-Bridge system 
[00:30:04] * #GrupoTDFork End
[00:40:38] -raymand- Could not forward: No such target matrirc
[01:05:50] * You are not on a channel, try /join #channel
[01:05:52] * You are not on a channel, try /join #channel

**Comment by PoincareMesh** [comment]
I run in kind of the same issue. I can join a room with irsii, but when I try to connect via ZNC bouncer I get:
`X> ListChans
<*status> +--------------+--------+-
<*status> | Name         | Status | 
<*status> +--------------+--------+-
<*status> | #SomeChannel | Trying | 
<*status> +--------------+--------+-
<*status> Total: 1, Joined: 0, Detached: 0, Disabled: 0
<*status> The channel #Reticulum could not be joined, disabling it.
<X> ListChans
<*status> +--------------+----------+-
<*status> | Name         | Status   | 
<*status> +--------------+----------+-
<*status> | #SomeChannel | Disabled | 
<*status> +--------------+----------+-`

**Comment by martinetd** [comment]
Sorry I didn't see a notification for the issue a few weeks ago.

I think they're different problems.


For the bouncer's issue, it's probably fairly straightforward -- matrirc currently ignores JOIN requests from the client as it didn't seem to matter for irssi and I just didn't do it; we just issue JOIN reports when there's activity.
I think if we actually process it the problem will go away (as per the trying/could not be joined messages it looks like client initiated join that timed out)
It's probably not too hard to add something in src/ircd/proto.rs' ircd_sync_read() that check if channel exists and trigger a join if it found it (the mapping isn't great, so I'd rather not make irc joins issue real matrix room joins if it wasn't found, some error should be given if not found)
I have very little time to work on this right now but I'll try to find time in the next few weeks

For the initial report thought I'm not sure; from the quote matrirc did send a JOIN report with users list, so the client ought to consider the chan joined; since it's doesn't the join is probably missing some info (there's a lot of optional things that can be sent on join and it perhaps expects a few more?)
What client is that?

**Comment by aiobofh** [comment]
Hi there, 

Hm

I use WeeChat directly connected to matrirc and when i try to join a channel using e.g. "/join #SomeChannel" i get:

irc: command "join" received without nick
irc: failed to parse command "join" (please report to developers): "JOIN #SomeChannel"

Is this related? 

I can only get PRIVMSG in "query-buffers" but no channels show up what so ever. :( Would be so awesome to get some hint on how to attend channels at all.

I get frequent Nick-lists from #SomeChannel in my server-buffer tho... So it seems matrirc is aware i am in these rooms. Also when people attach files in chat-rooms i get notifications in the server-buffer. But no conversations. So it's not like the normal messages in rooms are interleaved with eachother. Just gone.

Kind regards;
AiO

**Comment by martinetd** [comment]
So there's 2 things:
- /join from the client isn't handled (your first problem), matrirc just ignores the message -- I'm surprised at the error you got here as weechat shouldn't get any reply but it cannot work right now anyway so not much use looking further;
- the join messages from the server don't work (when there is a message or file in a channel, matrirc forcefully makes you join it before sendnig the message) -- there's probably some syntax error somewhere that'll be easy to fix if someone wants to compare at tcp level what you get from a working server; it's good to know weechat doesn't work with that I'll give it a try this weekend.

**Comment by aiobofh** [comment]
Aha. The force-join could just coincided with a manual try with /join - so you're probably correct. Could have been a coincidence,

I got the same Weechat error when i got an invite to a private chat from a new peer but "JOIN #ThePeersNickName". Hm.. Question on that... Is private chats ment to be channels instead of just private IRC messages? That would be more like other Matrix clients (and also would make it less cumbersome to join my good old Amiga IRC client to existing chats :D ) via the Weechat IRC-relay i have set-up. :)

**Comment by martinetd** [comment]
On the matrix side there's only channels, and matrirc doesn't really have a way to tell what is what -- the way it works right now is it's checking how many people are in the room, and if it's just you and someone else AND that someone else's display name matches the room name then messages will come in as query.
If someone else joins then it'll be promoted to channel and you'll be force joined.

On the reply from irc side, it actually doesn't care -- names are reserved for both, so if you're in a chat called ilovefrogs then you can send a query to ilovefrogs or send to #ilovefrogs channel and it'll be forwarded to the matrix channel regardless. (well, it looks like weechat might not let you send to a channel you're not joined unlike irssi)

Also because of #2 when you're joining a chan for some reason we're getting members duplicated so the first condition fails (too many members in room) and it's promoted to a channel, but if you reconnect to matrirc it'll be a channel.. I'm just not joining enough new channels to have bothered looking into it but some dedup shouldn't be too hard, now there actually seem to be users all of a sudden I might try to fix this (not complaining -- where did you all come from?)

**Comment by aiobofh** [comment]
I found your comment on some other ircd that talk matrix, here on Github, if I recall correctly something like "there is already this project, remove this comment if it's overreach" :D (it wasn't). Started my research on IRC:ing with Matrix again since matrix.py wont work with other weechat scripts that use SSL anymore due to Python-issues. :D And, to be honest. your software is WAY nicer approach than what I had. And the matrix.py is not relay:able as IRC, only as weechat-relay protocol. I even started coding an Amiga weechat-relay-client for that. For android the Weechat-relay client worked well enough... But. Now I don't have to do a complete client, since IRC clients already exist, thanks to your work :D 

On the topic of query/privmsg vesus channel for two-user-chat-rooms-as-channels... It would actually be neat with the second (as an option maybe?) since privmsg are not usually sent to multiple clients, like in my case where i use Weechat as a kind of bouncer in that sense. Privmsgs wont be available in several other IRC-clients connected to that IRC-relay in Weechat. There is some support for ZNC to prefix stuff and it tries to send privmsg to all connected clients somehow. But... Since a channel is more "matrix:y", why not? :D 

And again. THANK YOU for your work! I looked a bit at the source and I could probably help out if you want/need. But my Rust is Rusty :D (I'm mainly a C-kind-of-guy)

**Comment by martinetd** [comment]
> It would actually be neat with the second (as an option maybe?)

So, yes to that -- we definitely need to store some more state than the current src/state.rs (home server url & token); I think we need to remember which channels are currently joined and resend joins on reconnect (my irssi handles talking in a window that used to have a channel fine, but it's apparently not obvious, and it's silly to not be able to talk somewhere before someone else said something); it's probably not too hard to handle this kind of things as well.
We're also recomputing the available channels on every reconnect, but if there are collisions we'll stick a _2 around and there's no guarantee we'll get the same order everytime -- this all need to be remembered. It'd also make sense to allow renaming channels or whatever by talking to a fake bot like we do for invites..
The connection token is encrypted by the password sent on connect so we can't mess with this file (wouldn't want to remember that password), but this probably doesn't need to be encrypted so we can just create another file next to it with that.
... Anyway, I'm getting ahead of myself here, let's see if I can find time to fix the more pressing issues first.

> I looked a bit at the source and I could probably help out if you want/need. But my Rust is Rusty :D (I'm mainly a C-kind-of-guy)

I'm definitely doing much more C than rust as well, looks like we can get along..

Out of the issues that popped up earlier in this thread, the duplicated names on channel join (#2) is probably the easiest to fix -- src/matrix/room_mappings.rs fill_room_members room.members(ACTIVE) is fishy. I'm not sure if I misunderstood what active means or something else, but just adding logs with details of what's coming out of it and joining a new channel will probably get you enough infos to fix this (filter to dedup by matrix id?)
That ought to be a good place to start and it's independant enough from the other issues we have here that are all intermingled, and frankly chan management is a mess I'm not sure current me still understand, so probably would take as long to review than to just do it myself.

**Comment by martinetd** [comment]
Back to this issue, part 1 (what we're sending is weird), and now I'm checking it really is weird..

With a normal sever (user test, chan #testchan)
```
JOIN #testchan <-- that line from me
:test!test@myip JOIN :#testchan
:irc.test.org 353 test = #testchan :test @someone 
:irc.test.org 366 test #testchan :End of /NAMES list.
```

With matrirc
```
$ nc -v ::1 6668
Connection to ::1 6668 port [tcp/*] succeeded!
PASS xyz
NICK test2
USER foo1 foo2 foo3 foo4
:matrirc 001 test2 :Welcome to matrirc
...
PRIVMSG invite :yes <-- that line from me
:invite!invite@matrirc PRIVMSG test2 :Joining room test
:test_4!test_4@matrirc JOIN #test
JOIN #test
:matrirc 353 test2 = #test :test_3 test_2 test test_4 
:matrirc 366 test2 #test :End
:test_3!test_3@matrirc NOTICE #test :<invited test2>
:test_5!test_5@matrirc JOIN #test
:test!test@matrirc PRIVMSG #test :Joined room test
:test_3!test_3@matrirc PRIVMSG #test a
```
So there's quite a few differences:
- `:test_4!test_4@matrirc JOIN #test` has a weird prefix, it should be `:test2!foo1@matrirc` (host part is irrelevant)...
- (it doesn't have a colon before `#test`, but as far as I understand it's optional unless the channel name contains spaces, which isn't supported -- the irc crate we use should add it automatiically if required)
-  odd `JOIN #test` message without anchor?!
- #2 with nicks being odd, in this case I'd have expected test test_2 and test2 test2_2 (because I've made this room with two test accounts..) and it's made even worse because now there's even a join message after that, so one of these nicks is tripled! Well, some more dedups on matrix id for joins as well would do I guess.

I might not have time to finish this morning but I'll fix the stray unanchored message and the bad prefix, that should hopefully make weechat happy.

**Comment by martinetd** [comment]
Ah, so that test_4 JOIN was actually an external join like test_5 joining, and we're "just" not ordering it properly.. Because that join can take time (we need to enumerate members) I kicked it off to a separate task and this came to bite us.

I think it's ok to send that join message before the async join itself is finished as long as we send the "normal" join message first...
Alright, that's two bugs down.

Weechat also complained about "failed to parse command 329", I've fixed that too - I think it'll be a bit better. At the very least I've been able to reconnect to matrirc and talk to a room I had joined in a previous session without anyone else speaking in it first!

Next to implement joins from client to fix the ZNC issue brought up earlier, definitely not today but it's not that hard either, hopefully this weekend.

**Comment by aiobofh** [comment]
Wow, man! You're an energizer bunny!!!! Awesome work! Need to try it out.

**Comment by PoincareMesh** [comment]
I just pulled the new code and as soon as it was up, my ZNC reconnected and HexChat opened a bunch of 'Channels'.
Thank you so much, this makes my life a lot easier.
Where can I send some beer/coffee/...?

**Comment by martinetd** [comment]
Great! I'll still do joins initiated from clients but it looks like that can wait a bit longer then, I'll close this issue and have ope #15 for that separate problem.

>  Where can I send some beer/coffee/...?

Good question! I've never given it any thought but I've just submitted a request to open a github sponsor, let's see how that turns out.
I'll reply here again when it's done, thanks a lot for offering!

**Comment by martinetd** [comment]
@PoincareMesh Took a while but https://github.com/sponsors/martinetd finally got through if you're still interested in giving me a drink (there's a one-time mode)

I'm not holding my breath to be able to effectively tell $job I'll work one day less any soon but it cannot hurt to try!

**Comment by aiobofh** [comment]
Hm. I updated a while ago and i've experienced a few weirdnesses. But in general it seems to work. Every nick in the channel is duplicated... ni all channels, suffixed by "_2". . So in two-party-channels (like i normally use it) I am duplicated. there is an "AiO" and an "AiO_2" and also "Friend" and "Friend_2". I know you mentioned it at some point @martinetd - have your giant brain come any closer to a solution to this "quirk"? Looks like the other party always sends messages that end up as "Friend_2", also if i send messages in the channel from another client it's "AiO_2" talking in matriric.
